### ISSUE TITLE
Error: Error: Cannot find module './node_modules/coffee-script'

### ISSUE THREAD

**Issue by jeromevidaao** [paul-em/nogger#7]
I have the following error with the start command:

Error: Error: Cannot find module './node_modules/coffee-script'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nogger/node_modules/express.io/switch.js:5:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nogger/node_modules/daemonize2/lib/daemonize.js:136:19)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by alagu** [comment]
I'm facing this issue as well. @paul-em, any help here?

**Comment by paul-em** [comment]
Hey, probably some dependencies are outdated - this program was written quite a while ago with node 0.10 and I didn't update it since. I will try to push an update in the upcoming weeks

**Comment by paul-em** [comment]
New version is out - please give it a try
