### ISSUE TITLE
Error On Starting

### ISSUE THREAD

**Issue by amerireza** [paul-em/nogger#8]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at Liftoff.buildEnvironment (/usr/lib/node_modules/nogger/node_modules/liftoff/index.js:102:50)
    at Liftoff.launch (/usr/lib/node_modules/nogger/node_modules/liftoff/index.js:140:22)
    at Object.<anonymous> (/usr/lib/node_modules/nogger/bin/nogger.js:637:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

When I just run "nogger --help" and "sudo nogger --help" on my ubuntu 16.04 64 bit machin.

**Comment by Kenner-G** [comment]
I have the same issue! Someone please help!

**Comment by amerireza** [comment]
@kenner-g what is your problem? Explain your issue here.

**Comment by darren-white72** [comment]
I have also got the same issue

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/nogger/node_modules/liftoff/index.js:102:50)
    at Liftoff.launch (/usr/local/lib/node_modules/nogger/node_modules/liftoff/index.js:140:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/nogger/bin/nogger.js:630:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any idea when this will be fixed?
This looked a very nice tool to have but is no good if you cant pass any commands to the cli

**Comment by paul-em** [comment]
Hey, probably some dependencies are outdated - this program was written quite a while ago with node 0.10 and I didn't update it since. I will try to push an update in the upcoming weeks

**Comment by paul-em** [comment]
Hey guys, the new version is finally out. Please give it a try ;)
